/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDriverRouteRouteImport } from './routes/_authenticated/driver/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin/drivers'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin/enquiries'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin/invoices'
import { Route as AuthenticatedAdminReturnTripsRouteImport } from './routes/_authenticated/admin/return-trips'
import { Route as AuthenticatedAdminRidesRouteImport } from './routes/_authenticated/admin/rides'
import { Route as AuthenticatedAdminWalletsRouteImport } from './routes/_authenticated/admin/wallets'
import { Route as AuthenticatedDriverIndexRouteImport } from './routes/_authenticated/driver/index'
import { Route as AuthenticatedDriverDocumentsRouteImport } from './routes/_authenticated/driver/documents'
import { Route as AuthenticatedDriverPodRouteImport } from './routes/_authenticated/driver/pod'
import { Route as AuthenticatedDriverRequestsRouteImport } from './routes/_authenticated/driver/requests'
import { Route as AuthenticatedDriverReturnTripsRouteImport } from './routes/_authenticated/driver/return-trips'
import { Route as AuthenticatedDriverTripsRouteImport } from './routes/_authenticated/driver/trips'
import { Route as AuthenticatedDriverWalletRouteImport } from './routes/_authenticated/driver/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRouteRoute =
  AuthenticatedDriverRouteRouteImport.update({
    id: '/driver',
    path: '/driver',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReturnTripsRoute =
  AuthenticatedAdminReturnTripsRouteImport.update({
    id: '/return-trips',
    path: '/return-trips',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRidesRoute = AuthenticatedAdminRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminWalletsRoute =
  AuthenticatedAdminWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedDriverIndexRoute =
  AuthenticatedDriverIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedDriverDocumentsRoute =
  AuthenticatedDriverDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedDriverPodRoute = AuthenticatedDriverPodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => AuthenticatedDriverRouteRoute,
} as any)
const AuthenticatedDriverRequestsRoute =
  AuthenticatedDriverRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedDriverReturnTripsRoute =
  AuthenticatedDriverReturnTripsRouteImport.update({
    id: '/return-trips',
    path: '/return-trips',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedDriverTripsRoute =
  AuthenticatedDriverTripsRouteImport.update({
    id: '/trips',
    path: '/trips',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedDriverWalletRoute =
  AuthenticatedDriverWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/vehicles': typeof VehiclesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/driver': typeof AuthenticatedDriverRouteRouteWithChildren
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/return-trips': typeof AuthenticatedAdminReturnTripsRoute
  '/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/driver/documents': typeof AuthenticatedDriverDocumentsRoute
  '/driver/pod': typeof AuthenticatedDriverPodRoute
  '/driver/requests': typeof AuthenticatedDriverRequestsRoute
  '/driver/return-trips': typeof AuthenticatedDriverReturnTripsRoute
  '/driver/trips': typeof AuthenticatedDriverTripsRoute
  '/driver/wallet': typeof AuthenticatedDriverWalletRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/driver/': typeof AuthenticatedDriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/return-trips': typeof AuthenticatedAdminReturnTripsRoute
  '/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/driver/documents': typeof AuthenticatedDriverDocumentsRoute
  '/driver/pod': typeof AuthenticatedDriverPodRoute
  '/driver/requests': typeof AuthenticatedDriverRequestsRoute
  '/driver/return-trips': typeof AuthenticatedDriverReturnTripsRoute
  '/driver/trips': typeof AuthenticatedDriverTripsRoute
  '/driver/wallet': typeof AuthenticatedDriverWalletRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/driver': typeof AuthenticatedDriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/vehicles': typeof VehiclesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/driver': typeof AuthenticatedDriverRouteRouteWithChildren
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/return-trips': typeof AuthenticatedAdminReturnTripsRoute
  '/_authenticated/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/_authenticated/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/_authenticated/driver/documents': typeof AuthenticatedDriverDocumentsRoute
  '/_authenticated/driver/pod': typeof AuthenticatedDriverPodRoute
  '/_authenticated/driver/requests': typeof AuthenticatedDriverRequestsRoute
  '/_authenticated/driver/return-trips': typeof AuthenticatedDriverReturnTripsRoute
  '/_authenticated/driver/trips': typeof AuthenticatedDriverTripsRoute
  '/_authenticated/driver/wallet': typeof AuthenticatedDriverWalletRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/driver/': typeof AuthenticatedDriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/business'
    | '/cancellation-policy'
    | '/contact'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/track'
    | '/vehicles'
    | '/admin'
    | '/driver'
    | '/admin/documents'
    | '/admin/drivers'
    | '/admin/enquiries'
    | '/admin/invoices'
    | '/admin/return-trips'
    | '/admin/rides'
    | '/admin/wallets'
    | '/driver/documents'
    | '/driver/pod'
    | '/driver/requests'
    | '/driver/return-trips'
    | '/driver/trips'
    | '/driver/wallet'
    | '/admin/'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/business'
    | '/cancellation-policy'
    | '/contact'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/track'
    | '/vehicles'
    | '/admin/documents'
    | '/admin/drivers'
    | '/admin/enquiries'
    | '/admin/invoices'
    | '/admin/return-trips'
    | '/admin/rides'
    | '/admin/wallets'
    | '/driver/documents'
    | '/driver/pod'
    | '/driver/requests'
    | '/driver/return-trips'
    | '/driver/trips'
    | '/driver/wallet'
    | '/admin'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/business'
    | '/cancellation-policy'
    | '/contact'
    | '/how-it-works'
    | '/privacy'
    | '/terms'
    | '/track'
    | '/vehicles'
    | '/_authenticated/admin'
    | '/_authenticated/driver'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/return-trips'
    | '/_authenticated/admin/rides'
    | '/_authenticated/admin/wallets'
    | '/_authenticated/driver/documents'
    | '/_authenticated/driver/pod'
    | '/_authenticated/driver/requests'
    | '/_authenticated/driver/return-trips'
    | '/_authenticated/driver/trips'
    | '/_authenticated/driver/wallet'
    | '/_authenticated/admin/'
    | '/_authenticated/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BusinessRoute: typeof BusinessRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/return-trips': {
      id: '/_authenticated/admin/return-trips'
      path: '/return-trips'
      fullPath: '/admin/return-trips'
      preLoaderRoute: typeof AuthenticatedAdminReturnTripsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rides': {
      id: '/_authenticated/admin/rides'
      path: '/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AuthenticatedAdminRidesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/wallets': {
      id: '/_authenticated/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AuthenticatedAdminWalletsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/driver/': {
      id: '/_authenticated/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof AuthenticatedDriverIndexRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/driver/documents': {
      id: '/_authenticated/driver/documents'
      path: '/documents'
      fullPath: '/driver/documents'
      preLoaderRoute: typeof AuthenticatedDriverDocumentsRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/driver/pod': {
      id: '/_authenticated/driver/pod'
      path: '/pod'
      fullPath: '/driver/pod'
      preLoaderRoute: typeof AuthenticatedDriverPodRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/driver/requests': {
      id: '/_authenticated/driver/requests'
      path: '/requests'
      fullPath: '/driver/requests'
      preLoaderRoute: typeof AuthenticatedDriverRequestsRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/driver/return-trips': {
      id: '/_authenticated/driver/return-trips'
      path: '/return-trips'
      fullPath: '/driver/return-trips'
      preLoaderRoute: typeof AuthenticatedDriverReturnTripsRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/driver/trips': {
      id: '/_authenticated/driver/trips'
      path: '/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof AuthenticatedDriverTripsRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/driver/wallet': {
      id: '/_authenticated/driver/wallet'
      path: '/wallet'
      fullPath: '/driver/wallet'
      preLoaderRoute: typeof AuthenticatedDriverWalletRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminReturnTripsRoute: typeof AuthenticatedAdminReturnTripsRoute
  AuthenticatedAdminRidesRoute: typeof AuthenticatedAdminRidesRoute
  AuthenticatedAdminWalletsRoute: typeof AuthenticatedAdminWalletsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
    AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
    AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
    AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
    AuthenticatedAdminReturnTripsRoute: AuthenticatedAdminReturnTripsRoute,
    AuthenticatedAdminRidesRoute: AuthenticatedAdminRidesRoute,
    AuthenticatedAdminWalletsRoute: AuthenticatedAdminWalletsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDriverRouteRouteChildren {
  AuthenticatedDriverDocumentsRoute: typeof AuthenticatedDriverDocumentsRoute
  AuthenticatedDriverPodRoute: typeof AuthenticatedDriverPodRoute
  AuthenticatedDriverRequestsRoute: typeof AuthenticatedDriverRequestsRoute
  AuthenticatedDriverReturnTripsRoute: typeof AuthenticatedDriverReturnTripsRoute
  AuthenticatedDriverTripsRoute: typeof AuthenticatedDriverTripsRoute
  AuthenticatedDriverWalletRoute: typeof AuthenticatedDriverWalletRoute
  AuthenticatedDriverIndexRoute: typeof AuthenticatedDriverIndexRoute
}

const AuthenticatedDriverRouteRouteChildren: AuthenticatedDriverRouteRouteChildren =
  {
    AuthenticatedDriverDocumentsRoute: AuthenticatedDriverDocumentsRoute,
    AuthenticatedDriverPodRoute: AuthenticatedDriverPodRoute,
    AuthenticatedDriverRequestsRoute: AuthenticatedDriverRequestsRoute,
    AuthenticatedDriverReturnTripsRoute: AuthenticatedDriverReturnTripsRoute,
    AuthenticatedDriverTripsRoute: AuthenticatedDriverTripsRoute,
    AuthenticatedDriverWalletRoute: AuthenticatedDriverWalletRoute,
    AuthenticatedDriverIndexRoute: AuthenticatedDriverIndexRoute,
  }

const AuthenticatedDriverRouteRouteWithChildren =
  AuthenticatedDriverRouteRoute._addFileChildren(
    AuthenticatedDriverRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDriverRouteRoute: typeof AuthenticatedDriverRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDriverRouteRoute: AuthenticatedDriverRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BusinessRoute: BusinessRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
